### ISSUE TITLE
List of hindrances when starting to develop

### ISSUE THREAD

**Issue by mbercx** [aiidalab/aiidalab-docker-stack#183]
When starting to develop after running:

```
./run.sh 8888 ~/aiidalab
```

I run into a list of hindrances before I can really get to work. I'll keep track of them here. Not sure if these can be "fixed", but the steps to resolve them an get to work should be documented. Or a different pathway to starting to develop should be explained or easy to find.

- [x] Although the `apps` are installed in the `~/aiidalab` directory and hence easily accessible, you still have to change the ownership to your user before you can start adapting them or using e.g. git commands:
   ```
  (qeapp) mbercx@theospc46:~/aiidalab$ ls -l
  total 4
  drwxrwxr-x 5 administrator administrator 4096 Jun  5 09:49 apps
  ```
  Once I run:
  ```
  sudo chown -R mbercx:administrator apps/
  ```
  I'm in business! Maybe we can change the ownership in the setup?
- [x] For future releases that ship with the `aiidalab-qe-workchain`: immediately install this package in editable mode. This is really just for yours truly, but would be nice if I could skip the step to have to log in as root and do this. 😁 
- [x] Although upon initial deployment, the link+token is outputted so I can get to work right away, when I restart my computer for example I need to give the token again when I log in. If I hadn't kept this somewhere, I wouldn't really know how to proceed, except for restart the deployment.
- [x] The docker container now has a default generated name like `strange_dewdney` or `heuristic_wiles`. Is there a reason not to specify this name?

PS: I thought there were more when I first started opening this issue, but seems I just messed up a lot when I last set up this dev environment. 😅  Will still add anything I can think of to make the dev process smoother here.

**Comment by csadorf** [comment]
>  Although the apps are installed in the ~/aiidalab directory and hence easily accessible, you still have to change the ownership to your user before you can start adapting them or using e.g. git commands: 

The `~/aiidalab` directory (or whatever path you choose) is a bind mount and docker changes the ownership. It might be possible to prevent that, but I would need to look into how.

> For future releases that ship with the aiidalab-qe-workchain: immediately install this package in editable mode. This is really just for yours truly, but would be nice if I could skip the step to have to log in as root and do this.

I don't think there is a way around this, since for users of the app, the work chain must be installed independent of the app. Otherwise any update or re-installation of the app would break the environment.

**Comment by ltalirz** [comment]
docker container name fixed in 3977b7632775358a7239e146608921e1ce41d863 (name is `aiidalab`)

**Comment by ltalirz** [comment]
> * Although upon initial deployment, the link+token is outputted so I can get to work right away, when I restart my computer for example I need to give the token again when I log in. If I hadn't kept this somewhere, I wouldn't really know how to proceed, except for restart the deployment.

Good point (also, the token is not available from the `docker logs` of the container; it is replaced by `...` there).
In the use cases of the `run.sh` script that come to my mind, this additional layer of security is not actually needed, and [it is possible to disable token-based authentication by setting the token to an empty string](https://jupyter-notebook.readthedocs.io/en/stable/security.html#alternatives-to-token-authentication). 

I tried this - but it turns out that setting the token to an empty string in `run.sh` will actually cause the jupyter notebook server to generate its own token (which now is, sensibly, displayed in the logs).
The `run.sh` script could then get the url from the logs, e.g. using 
```bash
logs=`docker logs ${CONTAINER_ID} 2>&1 | tail -n1`
```
but this is somewhat fragile (and, in principle one still needs to replace the port 8888 by the one exposed by docker).

I think the best way to fix this would be to figure out how to disable the token-based authentication entirely, and make it possible from the `./run.sh` script to enable this mode.

**Comment by ltalirz** [comment]
> Although the apps are installed in the ~/aiidalab directory and hence easily accessible, you still have to change the ownership to your user before you can start adapting them or using e.g. git commands:

Just reporting that for me the directories and files are created with my system user (this is on MacOS 11.5.2 with Docker Desktop 3.6.0), i.e. for me this issue does not exist.

**Comment by csadorf** [comment]
@mbercx I believe that point 1 is somewhat addressed by using vscode for development and point 3 is addressed with the introduction of aiidalab-launch, would you agree?

**Comment by mbercx** [comment]
> would you agree?

Fully! Feel free to close this issue.

**Comment by csadorf** [comment]
> > would you agree?
> 
> Fully! Feel free to close this issue.

Great! 😃
