### ISSUE TITLE
AiiDAlab fails to start with error `File system loop detected; ‘/home/aiida/aiida’ is part of the same file system loop as ‘/home/aiida’.`

### ISSUE THREAD

**Issue by csadorf** [aiidalab/aiidalab-docker-stack#225]
After I clean the `.trash/` and rerun the `manage.py` I got:

```
...
aiidalab_1  | + verdi daemon stop
aiidalab_1  | Profile: default
aiidalab_1  | Warning: Deleted apparently stale daemon PID file as its associated process<1276> does not exist anymore
aiidalab_1  | Waiting for the daemon to shut down... The daemon was not running.
aiidalab_1  | + verdi database migrate --force
aiidalab_1  | + verdi daemon start
aiidalab_1  | Starting the daemon... RUNNING
aiidalab_1  | *** Running /etc/my_init.d/80_prepare-aiidalab.sh...
aiidalab_1  | + export SHELL=/bin/bash
aiidalab_1  | + SHELL=/bin/bash
aiidalab_1  | + '[' '!' -e /home/aiida/.ipython/profile_default/startup/aiida_magic_register.py ']'
aiidalab_1  | + '[' '!' -e /home/aiida/apps ']'
aiidalab_1  | + '[' '!' -e /home/aiida/apps/home ']'
aiidalab_1  | + [[ -d /home/aiida/apps/home ]]
aiidalab_1  | + [[ ! -L /home/aiida/apps/home ]]
aiidalab_1  | + [[ '' == 1 ]]
aiidalab_1  | + reentry scan
aiidalab_1  | + '[' -e /home/aiida/.trash ']'
aiidalab_1  | + find -L /home/aiida -maxdepth 3 -name apps_meta.sqlite -delete
aiidalab_1  | find: File system loop detected; ‘/home/aiida/aiida’ is part of the same file system loop as ‘/home/aiida’.
aiidalab_1  | *** /etc/my_init.d/80_prepare-aiidalab.sh failed with status 1
aiidalab_1  | 
aiidalab_1  | *** Killing all processes...
aiidalab_1  | Nov 15 12:48:07 53e6cb9c8379 syslog-ng[115]: syslog-ng shutting down; version='3.13.2'
aiidalab-docker-stack_aiidalab_1 exited with code 1
```

_Originally posted by @unkcpz in https://github.com/aiidalab/aiidalab-docker-stack/issues/223#issuecomment-968879111_

**Comment by csadorf** [comment]
@unkcpz @mbercx You both have reported experiencing this issue now. Could you please provide as much detail as possible as to what led up to the issue so that we can try to reproduce it?

**Comment by unkcpz** [comment]
There is a broken link file create in the aiidalab home volume during starting the docker compose:
```
lrwxrwxrwx   1 root          root             11 Nov 15 13:58 aiida -> /home/aiida
```

Where and when is this file created?

**Comment by csadorf** [comment]
> Where and when is this file created?

Using `ripgrep`, there are only three spots, where we explicitly symlink:

```console
~/local/aiidalab/aiidalab-docker-stack$ rg 'ln '
opt/prepare-aiidalab.sh
51:    ln -s /opt/aiidalab-home /home/${SYSTEM_USER}/apps/home
58:    && ln -s /opt/aiidalab-home /home/${SYSTEM_USER}/apps/home || echo "WARNING: Unable to install home app."

my_init.d/prepare-aiidalab.sh
5:ln -sf /home/${SYSTEM_USER} /project
```
I also checked [aiidateam/aiida-prerequisites](https://github.com/aiidateam/aiida-prerequisites) and [aiidateam/aiida-core](https://github.com/aiidateam/aiida-core/tree/develop/.docker), but did not find anything suspicious. So, I'm wondering whether this is maybe created through some weird mounting or so?

**Comment by ltalirz** [comment]
I'm experiencing the same issue.

A few further observations:

* It seems like every second time or so I also get this error:
```
*** Running /etc/my_init.d/10_syslog-ng.init...
Dec 22 09:21:39 0bc3b563ed69 syslog-ng[87]: syslog-ng starting up; version='3.13.2'
*** Running /etc/my_init.d/20_start-rabbitmq.sh...
 * Starting RabbitMQ Messaging Server rabbitmq-server
 * FAILED - check /var/log/rabbitmq/startup_\{log, _err\}
   ...fail!
*** /etc/my_init.d/20_start-rabbitmq.sh failed with status 1
```
By the way, it would seem to be useful to store the rabbitmq logs in ~/aiidalab/.rabbitmq rather than in /var/log in order to make them easier to inspect

* When one removes the looping `aiida` folder, it is recreated, i.e. effectively this bug blocks one from using the AiiDAlab altogether

**Comment by ltalirz** [comment]
The `Dockerfile` I was using had some modifications introduced by someone else who was pre-installing an application

```
COPY myapp /tmp/apps/myapp/
RUN chown -R 1000 /tmp/apps && chgrp -R 1000 /tmp/apps
```

After removing this it started working again...
I should mention though that it worked also *with* this modification before, so it's not clear to me yet what the source of the issue is.

**Comment by unkcpz** [comment]
The workaround for this is as @yakutovicha suggested, when start the container, keep on execute `rm -rf <aiida -> /home/aiida>` 😆 . I know it is a bit funny, but it works.

**Comment by yakutovicha** [comment]
> The workaround for this is as @yakutovicha suggested, when start the container, keep on execute `rm -rf <aiida -> /home/aiida>` 😆 . I know it is a bit funny, but it works.

I admit I am not proud of this "solution" 😆

**Comment by ltalirz** [comment]
One thing I notice:

If the aiidalab home volume isn't `aiidalab-home`, then the corresponding volume name under `volumes` is not associated with a volume.

```yaml
version: "3.8"
services:
  aiidalab:
    build:
      context: .
      args:
        - aiidalab_home_version=v21.10.0
    ports:
      - ${AIIDALAB_PORT:-8888}:8888
    environment:
      AIIDALAB_DEFAULT_APPS: ${AIIDALAB_DEFAULT_APPS:-aiidalab-widgets-base}
      JUPYTER_TOKEN: ${JUPYTER_TOKEN:-}
      SYSTEM_USER: ${SYSTEM_USER:-aiida}
    volumes:
      - "${AIIDALAB_HOME_VOLUME:-aiidalab-home}:/home/aiida"
volumes:
  aiidalab-home:
```

I guess the top-level `volumes` key is anyhow not needed, since we're currently not [reusing it across multiple services](https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes).

I do find the docker-compose syntax a bit puzzling, though: is it really true that the volume source must be used as the identifier in the top-level `volumes` section?
That seems like a weird choice to me...
