### ISSUE TITLE
Configure Jupyter server to kill idle python kernels

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab-docker-stack#378]
When the jupyter notebook server looses a connection to the frontend, it seems it will keep retrying indefinitely, which may lead to a memory leak as discussed in https://github.com/aiidalab/issues/issues/13. Moreover, it will leave the python kernel running indefinitely which needlessly consumes resources.

We need to configure the server to automatically kill inactive connections and kernels. Here are some resources on this:

https://discourse.jupyter.org/t/which-is-the-correct-way-to-cull-idle-kernels-and-notebook/8123
https://voila.readthedocs.io/en/latest/customize.html#cull-idle-kernels
https://github.com/jupyter/notebook/issues/4634

**Comment by danielhollas** [comment]
@unkcpz would you mind sharing the configuration for your deployment?

Here's what I planned to use in the Docker image for my app:

```dockerfile
ENV NOTEBOOK_ARGS \
     "${NOTEBOOK_ARGS}" \
     "--MappingKernelManager.buffer_offline_messages=True" \
     "--MappingKernelManager.cull_busy=True" \
     "--MappingKernelManager.cull_connected=True" \
     "--MappingKernelManager.cull_idle_timeout=64800" \
     "--MappingKernelManager.cull_interval=300" \
     "--TerminalManager.cull_inactive_timeout=600" \
     "--TerminalManager.cull_interval=60"
```

**Comment by unkcpz** [comment]
I set it in helm chart for k8s deployment here as https://github.com/aiidalab/aiidalab-microk8s-deploy/blob/c7405f774255560fb5adcede060dbf0f63502874/aiidalab/values.yml#L44-L49

I am not 100% sure it is working, in one deployment on MarketPlace, one day after I login, the container always need do start, I don't if it is because I set these parameters. 
You mentioned in the meeting when only open the home app it works but not for your app and QeApp. How do you find and confirm it is working as expected?

**Comment by unkcpz** [comment]
Just iterate what was mentioned by @cpignedoli, there is a way to force the kernel to live for at most 24h, correct? I think that is a feasible setting we can have. How to set that?

**Comment by danielhollas** [comment]
The settings that I posted above are exactly for that, the `cull_idle_timeout` is in seconds, the value above is for 12h, I think that is a reasonable compromise since one usually does not work more than 12 hours in a day. :-)

**Comment by cpignedoli** [comment]
I support the 12h idea
