### ISSUE TITLE
Add `rsync` in to the image

### ISSUE THREAD

**Issue by superstar54** [aiidalab/aiidalab-docker-stack#411]
We are testing the AiiDA backup script. In this `verdi storage backup` command, `rsync` is needed. Since the backup is very important, I suggest adding it to the image, so that users don't need to install using the root account. As pointed out by @unkcpz, the command will be lost if the image gets updated.

**Comment by danielhollas** [comment]
@superstar54 just so I understand, the `verdi storage backup` __itself__ needs `rsync`? Or do you need rsync to then copy the backup file?

Would you mind sharing the backup script? I needed something similar for our case so would be very interested.

Otherwise, I have no issue with adding rsync to the image (we just need to think about where in the stack it should live, `base` or `lab`?)

**Comment by superstar54** [comment]
Hi @danielhollas , please check this PR by Kristjan, https://github.com/aiidateam/aiida-core/pull/6069

**Comment by danielhollas** [comment]
Cool, thanks! Makes sense now.

**Comment by danielhollas** [comment]
I've added rsync as part of #439. So when aiiida-core v2.6 is release we should have a backup support!
