### ISSUE TITLE
Short minimum_job_poll_interval of localhost cause high CPU usage

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-docker-stack#462]
https://github.com/aiidalab/aiidalab-docker-stack/blob/c4b7a839e73638eedef7e2e368b447d9d7f2922c/stack/base/before-notebook.d/40_prepare-aiida.sh#L63

@cpignedoli reported a performance issue that the viscoscogy workflow launched the CPU usage is fully occupied by verdi, I guess this could be the source of the issue? 
Is `0.0` means keep on firing the commands to check? @sphuber

**Comment by sphuber** [comment]
This is the minimum interval that should be kept between opening of connections. Since here we are using `core.local` to connect to the localhost, it doesn't really make sense to have a limit on that. There is another polling interval that can be configured that is more important probably, and that is the minimum job poll interval defined on the computer:
```python
In [1]: load_computer('localhost').get_minimum_job_poll_interval()
Out[1]: 0.0
```
This interval determines how often the runner can check the scheduler to see if a job is done. I think is most likely the culprit. We should probably set it to 1 or something like that. Unfortunately, it can only be done through the API. There is no CLI endpoint yet.

There are multiple open related issues to this: #5638 #3630 #3541
I will have a look to see if I can implement this without having to rewrite/break too much

**Comment by danielhollas** [comment]
@unkcpz @cpignedoli it would be good if you could test that setting the minimum_job_poll_interval to 1s resolves the high CPU usage on the DEMO server. 
I believe this is also what I did in my local ATMOSPEC deployment, and I think we should set it in the image even before it gets implemented in aiida-core.

**Comment by unkcpz** [comment]
Thanks both! 

@danielhollas where did you run this change? Create a script and trigger it after setting the computer?

**Comment by danielhollas** [comment]
I've just modified the computer config after container startup.

**Comment by danielhollas** [comment]
@cpignedoli here's the relevant part of documentation

https://aiida.readthedocs.io/projects/aiida-core/en/stable/howto/run_codes.html#mitigating-connection-overloads

I think you just need to do the following in `verdi shell`

```python
load_computer('localhost').set_minimum_job_poll_interval(1.0)
```

If you still see high CPU load after than you can try increasing the interval further. Right now it's set to 0 I believe. :sweat_smile:

**Comment by cpignedoli** [comment]
Thanks a lot @danielhollas Indeed as a first reaction to my comment @unkcpz set it to 0.1 on May 17th and verdi % dropped to ~45%.
With poll 1 we get ~11%
With poll 5 ~ 3%

Is there any reason to keep the value smaller than 5 or 10?

**Comment by sphuber** [comment]
@cpignedoli the interval essentially tells the daemon workers how often they can check with the scheduler whether a job has finished. So if you set it 5 seconds, in the worst case, the worker will figures out a job finished 5 seconds after it had already finished. If you are not developing and running many small jobs and waiting for the results, those 5 seconds are not going to matter. So if you don't really care, it is fine to set it that high
